// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfbjZp3tYhcHPBMiZJZK2yjx2j0OXogF8',
    appId: '1:265291314133:web:8535cc7bec7423e38cc35c',
    messagingSenderId: '265291314133',
    projectId: 'nazdeeqi-doctor',
    authDomain: 'nazdeeqi-doctor.firebaseapp.com',
    storageBucket: 'nazdeeqi-doctor.firebasestorage.app',
    measurementId: 'G-94JSKW30L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqiKkd4h7hj7aFrgh_ASQpkNe6-Qt2anE',
    appId: '1:265291314133:android:efc9642a48d27e028cc35c',
    messagingSenderId: '265291314133',
    projectId: 'nazdeeqi-doctor',
    storageBucket: 'nazdeeqi-doctor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQo9RwJcBLBlxjvL45g0EpeIgTdCOnVOM',
    appId: '1:265291314133:ios:cd0997f1f90ee5b98cc35c',
    messagingSenderId: '265291314133',
    projectId: 'nazdeeqi-doctor',
    storageBucket: 'nazdeeqi-doctor.firebasestorage.app',
    iosBundleId: 'com.nazdeeqidoctor.nazdeeqiDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQo9RwJcBLBlxjvL45g0EpeIgTdCOnVOM',
    appId: '1:265291314133:ios:cd0997f1f90ee5b98cc35c',
    messagingSenderId: '265291314133',
    projectId: 'nazdeeqi-doctor',
    storageBucket: 'nazdeeqi-doctor.firebasestorage.app',
    iosBundleId: 'com.nazdeeqidoctor.nazdeeqiDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfbjZp3tYhcHPBMiZJZK2yjx2j0OXogF8',
    appId: '1:265291314133:web:863823ddd6e6f8eb8cc35c',
    messagingSenderId: '265291314133',
    projectId: 'nazdeeqi-doctor',
    authDomain: 'nazdeeqi-doctor.firebaseapp.com',
    storageBucket: 'nazdeeqi-doctor.firebasestorage.app',
    measurementId: 'G-L91CSSQP6Y',
  );
}
